version: '3.8'

services:
  rtcwebapp:
    build: .
    container_name: rtcwebapp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rtcwebapp.rule=Host(`cam.punkydev.fr`)"
      - "traefik.http.routers.rtcwebapp.entrypoints=websecure"
      - "traefik.http.routers.rtcwebapp.tls.certresolver=letsencrypt"
      - "traefik.http.services.rtcwebapp.loadbalancer.server.port=7162"
      - "traefik.http.services.rtcwebapp.loadbalancer.server.scheme=https"
      - "traefik.http.services.rtcwebapp.loadbalancer.server.insecureSkipVerify=true"
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    external: true
